### ISSUE TITLE
make a yarn package

### ISSUE THREAD

**Issue by chiptus** [dsifford/yarn-completion#2]
add the ability to run ```yarn add yarn-completion``` to run this script

**Comment by dsifford** [comment]
@chiptus Just confirming: Are you requesting that this be published to the npm registry so that you can install using `yarn add ...`?

If so, although I can certainly do that, running `yarn add yarn-completion` won't add the file to the correct location.

I can perhaps make a package.json script to install the file to the right place however. But having said that, there are a few different ways you can use install it:
1. Add to `/etc/bash_completion.d/`
2. Copy directly to  `.bashrc`.
3. Source from file in `.bashrc`.
4. Source in the active session.

Let me know. Thanks 👍

**Comment by dsifford** [comment]
@chiptus Updated the readme with two-step install instructions. 

Closing this since I haven't heard back. Feel free to reopen if this doesn't work for you. 👍
